name: Code Coverage

on:
  pull_request:
    branches: ['**']
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921
      with:
        toolchain: stable

    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Generate code coverage
      run: cargo tarpaulin --out Xml --output-dir ./coverage --run-types Tests,Doctests --all-features -- --include-ignored
      env:
        BSV_NODE_URL: ${{ secrets.BSV_NODE_URL }}
        BSV_NODE_USER: ${{ secrets.BSV_NODE_USER }}
        BSV_NODE_PASSWORD: ${{ secrets.BSV_NODE_PASSWORD }}

    - name: Upload coverage to Codacy
      uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage/cobertura.xml
