name: Rust CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921
      with:
        toolchain: stable
        components: rustfmt

    - name: Run cargo check
      run: cargo check

    - name: Run cargo fmt
      run: cargo fmt -- --check
